// Embeds a Fusion Pixel subset into a canvas game: node tools/game-font.mjs tbmh
// Collects every character in <game>/index.html and <game>/js/*.js, subsets the
// 12 px face to them and the 8 px face to printable ASCII, and writes
// <game>/js/font.js as base64 so the game also runs from file://.
import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import { embeddedFont, collectCharacters, missingGlyphs } from './font-data.mjs';
import subsetFont from './.deps/node_modules/subset-font/index.js';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const game = process.argv[2] || 'tbmh';
const js = path.join(root, game, 'js');
const files = [path.join(root, game, 'index.html'), ...readdirSync(js).filter(f => f.endsWith('.js') && f !== 'font.js').sort().map(f => path.join(js, f))];
const text = collectCharacters(files);
const ascii = Array.from({ length: 95 }, (_, i) => String.fromCodePoint(0x20 + i)).join('');
const fp12 = embeddedFont(root, 'fp12'), fp8 = embeddedFont(root, 'fp8');
const missing = missingGlyphs(fp12, text);
if (missing.length) {
  console.error('Fusion Pixel 12px lacks: ' + missing.join(' '));
  process.exit(1);
}
const out12 = await subsetFont(fp12, text, { targetFormat: 'woff2' });
const out8 = await subsetFont(fp8, ascii, { targetFormat: 'woff2' });
if (missingGlyphs(out12, text).length || missingGlyphs(out8, ascii).length) throw new Error('subset coverage');
writeFileSync(path.join(js, 'font.js'),
  '// Fusion Pixel Font subset (SIL OFL 1.1) — generated by tools/game-font.mjs, do not edit.\n' +
  '// https://github.com/TakWolf/fusion-pixel-font · license: entropy-blade/fonts/OFL-fusion-pixel.txt\n' +
  `window.TBMH_FONT = { fp12: '${out12.toString('base64')}', fp8: '${out8.toString('base64')}' };\n`);
console.log(`${game} font: ${[...text].length} characters, 12px ${out12.length} B, 8px ${out8.length} B.`);
