'use strict';
// =====================================================================
//  ART · ITEMS — equipment icons (recolored by material tier and
//  grade), the hunter's held weapons and off-hands, materials, chests,
//  skill and UI icons, projectiles. Letters: m metal, l leather/cloth,
//  b handle, g trim, e grade gem.
// =====================================================================
(() => {
  const { RAMP, def, VARIANTS } = ART, P = PAL;
  const ICON = { ox: 0, oy: 0 };
  const EQ = { m: RAMP.silver, l: RAMP.brown, b: RAMP.wood, g: RAMP.gold, e: P.steel, s: P.cream, o: RAMP.ice, W: P.white, k: P.ink, f: P.red, t: P.mist };

  // ---------------- main hand ----------------
  def('w_bow', EQ, [`
................
...........mmmm.
.........mmm.s..
.......mmm..s...
......mm...s....
.....ge...s.....
....gg...s......
...mm...s.......
...m...s........
..mm..s.........
..m..s..........
.mm.s...........
.m.s............
.ms.............
.m..............
................`], ICON);
  def('w_crossbow', EQ, [`
................
................
................
...........m....
............m...
.............m..
bbbbbbbbbbbbbbtt
bbbebbbbbbbbbm..
..bb........m...
..bb.......m....
..bb............
................
................
................
................
................`], ICON);
  def('w_staff', EQ, [`
............ooo.
...........oWooo
...........ooooo
..........m.ooo.
.........m.m....
........b.m.....
.......b........
......b.........
.....b..........
....g...........
...b............
..b.............
.b..............
b...............
................
................`], ICON);
  def('w_scepter', EQ, [`
............m...
..........mmmm..
.........mmmmmm.
........mmmeemmm
.........mmeemm.
..........mmmm..
.........b......
........b.......
.......b........
......b.........
.....b..........
....g...........
...b............
..b.............
.g..............
................`], ICON);
  Object.assign(ART.GRIP, { w_bow: [5, 6], w_crossbow: [3, 8], w_staff: [9, 9], w_scepter: [4, 11] });

  // ---------------- off hand ----------------
  def('o_shield', EQ, [`
................
..mmmmmmmmmmmm..
..mllllllllllm..
..mlllleellllm..
..mllleeeelllm..
..mlllleellllm..
..mllllllllllm..
...mllllllllm...
...mllllllllm...
....mllllllm....
.....mllllm.....
......mllm......
.......mm.......
................
................
................`], ICON);
  def('o_hatchet', EQ, [`
................
.........mm.....
........mmmm....
.......mmmmmm...
......bmmmmmm...
.....b.mmmmm....
....b...mmm.....
...b............
..l.............
.l..............
e...............
................
................
................
................
................`], ICON);
  def('o_quiver', EQ, [`
.....f.f.f......
....fffffff.....
.....s.s.s......
....mmmmmmm.....
....lllllll.....
....llleell.....
....lllllll.....
....lllllll.....
....llmmmll.....
....lllllll.....
....lllllll.....
.....lllll......
......mmm.......
................
................
................`], ICON);
  def('o_bolts', EQ, [`
................
....m.m.m.......
....t.t.t.......
...mmmmmmm......
...lllllll......
...lleelll......
...lllllll......
...lllllll......
...mmmmmmm......
...lllllll......
....lllll.......
................
................
................
................
................`], ICON);
  def('o_orb', EQ, [`
................
......oooo......
.....oooooo.....
....ooWoooo.....
....oWoooooo....
....oooooooo....
.....oooooo.....
......oooo......
.....mm..mm.....
......mmmm......
.......ee.......
......mmmm......
.....mmmmmm.....
................
................
................`], ICON);
  def('o_tome', EQ, [`
................
...mllllllllm...
...llllllllls...
...lllleellls...
...llleeeells...
...lllleellls...
...llllllllls...
...mllllllllm...
....ssssssss....
................
................
................
................
................
................
................`], ICON);

  // ---------------- armor ----------------
  def('a_helm', EQ, [`
......lll.......
.....mmmmmm.....
....mmmmmmmm....
...mmmmmmmmmm...
...mmmmmmmmmm...
...mkkkkkkkkm...
...mmmmmmmmmm...
...mmmmeemmmm...
...mmmmmmmmmm...
....mmmmmmmm....
...mm......mm...
................
................
................
................
................`], ICON);
  def('a_chest', EQ, [`
................
.mmm........mmm.
mmmmmm....mmmmmm
mmmmmmmmmmmmmmmm
.mmmMmmmmmmmMmm.
...mmMmmmmMmmm..
...mmmMmmMmmmm..
...mmmmMMmmmmm..
...mmmmgemmmmm..
...mmmmmgmmmmm..
....mmmmmmmmmm..
....mMMMMMMMMm..
....mmmmmmmmmm..
.....mm....mm...
................
................`], ICON);
  def('a_gloves', EQ, [`
................
...m.m.m........
...m.m.m.m......
...mmmmmmm......
...mmmmmmm.mm...
...mmmmmmmmmm...
...mmmmmmmmm....
....mmmmmmm.....
....lllllll.....
....llleell.....
....lllllll.....
................
................
................
................
................`], ICON);
  def('a_boots', EQ, [`
................
.....llll.......
.....llll.......
.....llll.......
.....mmmm.......
.....llll.......
.....lllll......
.....lllllelll..
....lllllllllm..
....mmmmmmmmmm..
................
................
................
................
................
................`], ICON);

  // ---------------- accessories ----------------
  def('c_earring', EQ, [`
................
.......mm.......
......m..m......
......m..m......
.......mm.......
.......m........
......eee.......
.....eeWee......
......eee.......
.......e........
................
................
................
................
................
................`], ICON);
  def('c_bracer', EQ, [`
................
................
................
...mmmmmmmmmm...
..mllllllllllm..
..mlllleellllm..
..mllllllllllm..
..mllllllllllm..
...mmmmmmmmmm...
................
................
................
................
................
................
................`], ICON);

  // ---------------- held in the hunter's hands (facing right) ----------------
  def('h_bow', EQ, [`
mm....
.mm...
s.mm..
s..m..
s..mm.
s...m.
s...g.
s...ge
s...g.
s...m.
s..mm.
s..m..
s.mm..
.mm...
mm....`], { ox: 4, oy: 7 });
  def('h_xbow', EQ, [`
..........m...
...........m..
bbbbbbbbbbbbtt
bbbebbbbbbbm..
..bb......m...
..bb..........`], { ox: 3, oy: 4 });
  def('h_staff', EQ, [`
..ooo..
.oWooo.
.ooooo.
..ooo..
.m.b.m.
..mbm..
...b...
...g...
...b...
...b...
...b...
...b...
...b...
...b...
...b...
...b...
...b...
...b...
...g...`], { ox: 3, oy: 12 });
  def('h_shield', EQ, [`
mmmmmmm
mllellm
mleeelm
mllellm
.mlllm.
.mlllm.
..mlm..
...m...`], { ox: 3, oy: 4 });
  def('h_quiver', EQ, [`
f.f..
fff..
.s.s.
mmmm.
llll.
llll.
llll.
mmmm.
.ll..`], { ox: 2, oy: 4 });
  def('h_bolts', EQ, [`
m.m.
mmmm
llll
llll
mmmm`], { ox: 2, oy: 2 });
  def('h_hatchet', EQ, [`
.mm..
mmmm.
mmmb.
.mb..
..b..
..l..`], { ox: 2, oy: 3 });
  def('h_orb', { o: RAMP.ice, W: P.white }, [`
.ooo.
oWooo
ooooo
.ooo.`], { ox: 2, oy: 2 });
  def('h_tome', EQ, [`
mllll.
lleels
llllls
mllll.`], { ox: 3, oy: 2 });

  // ---------------- materials (12 px) ----------------
  def('i_gem', { g: RAMP.red, W: P.white }, [`
....gggg....
...gWWggg...
..gWggggGg..
.gggggggGGg.
gggggggggGGg
.gggggggGGg.
..ggggggGg..
...gggggg...
....gggg....`], ICON);
  VARIANTS.i_gem = { ruby: { g: RAMP.red }, sapphire: { g: RAMP.blue }, topaz: { g: RAMP.gold }, emerald: { g: RAMP.green }, amethyst: { g: RAMP.purple } };
  const PART_SHAPES = {
    part_fang: `
..........aa
.........aaa
........aaa.
.......aaa..
......aaa...
.....aaa....
....aaaa....
...aaaaa....
..aaaaa.....
.aaaaa......
.aaaa.......
..aa........`,
    part_hide: `
.aa......aa.
aaaaaaaaaaaa
.aaaaaaaaaa.
..aaaaaaaa..
..aaAaaAaa..
..aaaaaaaa..
.aaaaaaaaaa.
aaaaaaaaaaaa
.aa......aa.`,
    part_goo: `
.....a......
....aaa.....
...aaaaa....
..aaWaaaa...
.aaWaaaaaa..
.aaaaaaaaa..
.aaaaaaaaa..
..aaaaaaa...
...aaaaa....`,
    part_wing: `
.........aa.
........aaa.
.......aAaa.
......aAaa..
.....aAaa...
....aAaa....
...aAaa.....
..aAaa......
..Aaa.......
.A..........
A...........`,
    part_core: `
....aaaa....
..aaaaaaaa..
.aaWWaaaaaa.
.aWaaaaaaaa.
aaaaaaaaaaaa
aaaaaaaaaaAa
.aaaaaaaaAa.
.aaaaaaaAAa.
..aaaaaaaa..
....aaaa....`,
    part_bone: `
aa..........
aaa.........
.aaa........
..aaa.......
...aaa......
....aaa.....
.....aaa....
......aaa...
.......aaa..
........aaaa
.........aaa
..........aa`,
  };
  for (const k in PART_SHAPES) def(k, { a: RAMP.bone, W: P.white }, [PART_SHAPES[k]], ICON);
  // which shape and ramp each monster family's part uses
  const PART_LOOK = {
    p_slime: ['part_goo', RAMP.green], p_rabbit: ['part_fang', RAMP.bone], p_insect: ['part_hide', RAMP.gold], p_goblin: ['part_hide', RAMP.green],
    p_shroom: ['part_goo', RAMP.red], p_bat: ['part_wing', RAMP.purple], p_plant: ['part_goo', RAMP.moss], p_spider: ['part_wing', RAMP.cloud],
    p_fox: ['part_core', RAMP.fire], p_troll: ['part_fang', RAMP.bone], p_scorpion: ['part_fang', RAMP.fire], p_snake: ['part_hide', RAMP.teal],
    p_mummy: ['part_hide', RAMP.bone], p_rat: ['part_core', RAMP.ink], p_wolf: ['part_fang', RAMP.cloud], p_beast: ['part_hide', RAMP.cloud],
    p_frost: ['part_core', RAMP.ice], p_skeleton: ['part_bone', RAMP.bone], p_penguin: ['part_wing', RAMP.navy], p_ghost: ['part_core', RAMP.ghost],
    p_undead: ['part_fang', RAMP.moss], p_frog: ['part_goo', RAMP.moss], p_golem: ['part_core', RAMP.steel], p_mole: ['part_core', RAMP.gold],
    p_crystal: ['part_core', RAMP.purple], p_demon: ['part_fang', RAMP.red], p_lizard: ['part_hide', RAMP.fire], p_flame: ['part_core', RAMP.lava],
    p_worm: ['part_hide', RAMP.dark], p_bird: ['part_wing', RAMP.sand], p_sky: ['part_goo', RAMP.cloud], p_gargoyle: ['part_core', RAMP.red],
    p_knight: ['part_hide', RAMP.silver], p_eye: ['part_core', RAMP.red], p_drake: ['part_bone', RAMP.bone], p_cult: ['part_hide', RAMP.purple],
  };
  for (const k in PART_SHAPES) VARIANTS[k] = {};
  for (const id in PART_LOOK) VARIANTS[PART_LOOK[id][0]][id] = { a: PART_LOOK[id][1] };
  ART.PART_LOOK = PART_LOOK;
  def('i_scroll', { p: RAMP.sand, k: P.bark, e: P.red }, [`
..pppppppp..
.pPPPPPPPPp.
..pppppppp..
..pkkkkkkp..
..pppppppp..
..pkkkkkpp..
..pppppppp..
..pkkkkkkp..
.pppppppppp.
.pPPPPeePPp.
..pppeeppp..`], ICON);
  def('i_ore', { a: RAMP.steel, W: P.white }, [`
...aaaaaa...
..aWaaaaaa..
.aWaaaaaaaa.
aaaaaaaaaaaa
AAAAAAAAAAAA
AAAAAAAAAAAA`], ICON);
  VARIANTS.i_ore = {};
  [RAMP.wood, RAMP.brown, RAMP.steel, RAMP.silver, RAMP.gold, RAMP.ice, RAMP.cloud, RAMP.purple, RAMP.fire, RAMP.teal].forEach((r, i) => (VARIANTS.i_ore[i] = { a: r }));
  def('i_chaos', { c: RAMP.purple, W: P.white }, [`
.....c......
....ccc.....
...cccWc....
..cccccc....
...ccccc....
....cccc....
...ccccc....
..cccccc....
...cccc.....
....cc......`], ICON);
  def('i_coin', { g: RAMP.gold, e: P.steel, k: P.bark, W: P.white }, [`
....eeee....
..eeggggee..
.egWgggggge.
.eWggkkggge.
egggkkkkggge
eggkkkkkkgge
egggkkkkggge
.egggkkggge.
.egggggggge.
..eeggggee..
....eeee....`], ICON);
  def('i_wanted', { p: RAMP.sand, k: P.bark, r: P.red }, [`
pppppppppppp
pPPPPPPPPPPp
pppkkkkkkppp
ppkkpkkpkkpp
ppkkkkkkkkpp
pppkkpkkkppp
pppkkkkkkppp
pppppppppppp
prrrrrrrrrrp
pppppppppppp
pPPPPPPPPPPp`], ICON);
  VARIANTS.i_wanted = { 0: { r: P.steel }, 1: { r: P.magenta }, 2: { r: P.red }, 3: { r: P.amber } };

  // ---------------- chests ----------------
  def('chest', { w: RAMP.wood, m: RAMP.steel, g: P.amber, y: P.yellow, Y: P.white }, [`
................
...wwwwwwwwww...
..wwwwwwwwwwww..
.wwwwwwwwwwwwww.
.mmmmmmmmmmmmmm.
.wwwwwwggwwwwww.
.WWWWWWggWWWWWW.
.wwwwwwwwwwwwww.
.wwwwwwwwwwwwww.
.mwwwwwwwwwwwwm.
.mwwwwwwwwwwwwm.
.mmmmmmmmmmmmmm.`, `
..wwwwwwwwwwww..
.wWWWWWWWWWWWWw.
.mmmmmmmmmmmmmm.
.yyyyYYYYYYyyyy.
.yyyyyyyyyyyyyy.
.wwwwwwggwwwwww.
.WWWWWWggWWWWWW.
.wwwwwwwwwwwwww.
.wwwwwwwwwwwwww.
.mwwwwwwwwwwwwm.
.mwwwwwwwwwwwwm.
.mmmmmmmmmmmmmm.`], { ox: 8, oy: 11 });
  VARIANTS.chest = { 0: { w: RAMP.wood, m: RAMP.steel, g: P.amber }, 1: { w: RAMP.red, m: RAMP.silver, g: P.yellow }, 2: { w: RAMP.purple, m: RAMP.gold, g: P.cyan } };

  // ---------------- skill icons (16 px) ----------------
  const SK = (name, pal, art) => def(name, pal, [art], ICON);
  SK('s_bash', { s: RAMP.silver, b: RAMP.blue, y: P.yellow, w: P.white }, `
..........y.....
.........y.y..y.
..........y..y..
..sssssss....y..
..sbbbbbs.yy....
..sbbwbbs.......
..sbbbbbs..yyy..
..sbbbbbs.......
...sbbbs...y....
...sbbbs..y.y...
....sbs.....y...
.....s..........
................
................
................
................`);
  SK('s_bladestorm', { s: RAMP.ice, w: P.white }, `
......ss........
.......ss.......
........ss......
...s.....s......
..ss......s.....
.ss........s....
ss..........ss..
...ss....ss.....
.....ssss.......
.ss....ss....ss.
...s.......sss..
....s....ss.....
.....s.ss.......
......ss........
.......ss.......
................`);
  SK('s_riposte', { s: RAMP.silver, r: RAMP.red, b: RAMP.wood }, `
s..............s
.s............s.
..s..........s..
...s........s...
....s......s....
.....s....s.....
......s..s......
.......ss.......
......s..s......
.....b....b.....
....b......b....
...b..rrrr..b...
.....rr..rr.....
....rr....r.....
.....r...rrr....
..........r.....`);
  SK('s_whirl', { m: RAMP.silver, b: RAMP.wood, w: RAMP.ice }, `
....wwwwww......
..ww......ww....
.w....mm....w...
w....mmmm....w..
w....mmmmb...w..
w.....mmb....w..
w......b.....w..
.w....b.....w...
..w..b.....w....
...wb....ww.....
...b.wwww.......
..b.............
.b..............
................
................
................`);
  SK('s_throwaxe', { m: RAMP.silver, b: RAMP.wood, w: P.cyan }, `
................
..........mmm...
.........mmmmm..
........bmmmmm..
.......b..mmm...
......b.........
.....b..........
w.....w.........
.w......w.......
..w.......w.....
...ww.......ww..
.....wwwwwww....
................
................
................
................`);
  SK('s_crush', { m: RAMP.steel, b: RAMP.wood, k: P.bark, y: P.yellow }, `
....mmmmm.......
...mmmmmmm......
...mmmmmmm......
....mmmmm.......
.......b........
........b.......
.........b......
..........b.....
...........b....
....y.......b...
...yyy...y......
kkkkkkkkkkkkkkkk
.k..k.kk..k..k..
k..k...k.k..k..k
................
................`);
  SK('s_rage', { r: RAMP.red, f: RAMP.fire, k: P.ink, w: P.white }, `
...f...f...f....
..fff.fff.fff...
..frrrrrrrrrf...
.frrrrrrrrrrrf..
.rrkkrrrrrkkrr..
.rrrkkrrrkkrrr..
.rrrrrrrrrrrrr..
.rrrkkkkkkkrrr..
.rrrkwwwwwkrrr..
..rrrkkkkkrrr...
...rrrrrrrrr....
.....rrrrr......
................
................
................
................`);
  SK('s_cleaver', { m: RAMP.silver, b: RAMP.wood, r: P.red }, `
................
..mmmmmmmmm.....
.mmmmmmmmmmm....
.mmmmmmmmmmmm...
.mmmmmmmmmmmm...
.mmmmmmmrmmmm...
.mmmmmmmmmmmbb..
..mmmmmmmmm..bb.
..............bb
................
................
................
................
................
................
................`);
  SK('s_pierceshot', { s: P.cream, m: RAMP.silver, f: P.red, c: RAMP.ice }, `
................
.....c....c.....
....c.c..c.c....
...c...cc...c...
ff.c...cc...c...
ffssssssssssssmm
ff.c...cc...c...
...c...cc...c...
....c.c..c.c....
.....c....c.....
................
................
................
................
................
................`);
  SK('s_arrowrain', { s: P.cream, m: RAMP.silver, f: P.red, k: P.bark }, `
.f......f.....f.
.s...f..s..f..s.
.s...s..s..s..s.
.s...s..m..s..s.
.m...s..m..s..m.
.m...m.....m..m.
.....m.....m....
...f.....f......
...s.....s......
...s.....s......
...m.....m......
...m.....m......
................
kkkkkkkkkkkkkkkk
................
................`);
  SK('s_rapid', { s: P.cream, m: RAMP.silver, f: P.red }, `
................
................
ff..............
ffssssssssssmm..
ff..........mm..
................
................
....ff..........
....ffssssssssmm
....ff........mm
................
................
................
................
................
................`);
  SK('s_hawkeye', { w: RAMP.cloud, i: RAMP.gold, k: P.ink }, `
................
................
................
.....wwwwww.....
...wwwwwwwwww...
..wwwiiiiiwwww..
.wwwiikkkiiwwww.
.wwwikkkkkiwwww.
.wwwiikkkiiwwww.
..wwwiiiiiwwww..
...wwwwwwwwww...
.....wwwwww.....
................
................
................
................`);
  SK('s_snipe', { r: RAMP.red, w: P.white }, `
.......r........
.......r........
.....rrrrr......
....r..r..r.....
...r...r...r....
...r.......r....
rrrrrr.w.rrrrrr.
...r.......r....
...r...r...r....
....r..r..r.....
.....rrrrr......
.......r........
.......r........
................
................
................`);
  SK('s_repeater', { s: P.cream, m: RAMP.steel, f: P.amber }, `
................
f...............
fsssssssmmm.....
f...............
..f.............
..fsssssssmmm...
..f.............
....f...........
....fsssssssmmm.
....f...........
................
................
................
................
................
................`);
  SK('s_ap', { m: RAMP.steel, r: RAMP.red, k: P.ink }, `
................
..mmmmmmmmmm....
..mmmmmkmmmm....
..mmmmkmmmmm....
..mmmmmkmmmm....
..mmmmkkmmmm....
...mmmmmkmm.....
...mmmmkmmm.....
....mmmmmm......
.....mmmm.......
rrrrrrrrrrrrrr..
.....mm.........
................
................
................
................`);
  SK('s_fireball', { f: RAMP.fire, y: P.yellow, w: P.white }, `
................
...........ff...
.........fff....
.......ffff.....
.....ffffff.....
...fffffffff....
..fffyyyyfff....
..ffyywwyyff....
..ffyywwyyff....
..fffyyyyfff....
...ffffffff.....
....ffffff......
................
................
................
................`);
  SK('s_frostnova', { c: RAMP.ice, w: P.white }, `
.......c........
....c..c..c.....
.....c.c.c......
..c...ccc...c...
...c..ccc..c....
....cccwccc.....
.cccccwwwccccc..
....cccwccc.....
...c..ccc..c....
..c...ccc...c...
.....c.c.c......
....c..c..c.....
.......c........
................
................
................`);
  SK('s_hydra', { g: RAMP.fire, k: P.ink, y: P.yellow }, `
..gg....gg...gg.
.ggkg..gkgg.gkgg
.gggg..gggg.gggg
.gg....gg....gg.
.gg....gg....gg.
..gg...gg...gg..
...gg..gg..gg...
....gggggggg....
.....gggggg.....
....gggggggg....
...gggggggggg...
................
................
................
................
................`);
  SK('s_elem', { r: RAMP.fire, b: RAMP.ice, y: RAMP.gold }, `
................
.....rrr........
....rrrrr.......
....rrrrr.......
.....rrr........
................
..bbb.....yyy...
.bbbbb...yyyyy..
.bbbbb...yyyyy..
..bbb.....yyy...
................
................
................
................
................
................`);
  SK('s_surge', { b: RAMP.blue, w: P.white }, `
......bbbb......
....bb....bb....
...b..bbbb..b...
..b..b....b..b..
..b.b..bb..b.b..
..b.b.bwwb.b.b..
..b.b.bwwb.b.b..
..b.b..bb..b.b..
..b..b....b..b..
...b..bbbb..b...
....bb....bb....
......bbbb......
................
................
................
................`);
  SK('s_smite', { y: RAMP.gold, w: P.white, m: RAMP.silver }, `
.......y........
...y...y...y....
....y..y..y.....
.....mmmmm......
....mmmmmmm.....
yy..mmmwmmm..yy.
....mmmmmmm.....
.....mmmmm......
.......m........
.......m........
.......m........
.......m........
......mmm.......
................
................
................`);
  SK('s_prayer', { y: RAMP.gold, s: RAMP.skin, w: P.white }, `
.......y........
...y...w...y....
....y.www.y.....
.......w........
......s.s.......
.....ss.ss......
.....ss.ss......
....sss.sss.....
....sss.sss.....
...ssss.ssss....
...sssssssss....
....sssssss.....
................
................
................
................`);
  SK('s_aura', { y: RAMP.gold, w: P.white }, `
.....yyyyyy.....
...yy......yy...
..y..yyyyyy..y..
.y..y......y..y.
.y.y..wwww..y.y.
y..y.ww..ww.y..y
y..y.w....w.y..y
y..y.ww..ww.y..y
.y.y..wwww..y.y.
.y..y......y..y.
..y..yyyyyy..y..
...yy......yy...
.....yyyyyy.....
................
................
................`);
  SK('s_regen', { g: RAMP.green, w: P.white }, `
................
......gggg......
......gwgg......
......gggg......
......gggg......
.gggggggggggggg.
.gwwgggggggggg..
.gggggggggggggg.
......gggg......
......gggg......
......gggg......
......gggg......
................
................
................
................`);

  // ---------------- UI icons (9 px) ----------------
  def('i_cube', { c: RAMP.purple, w: P.white }, [`
....c....
..ccccc..
ccccwcccc
cccwwwccc
CccccccCC
CCcccccCC
CCCcccCCC
.CCCcCCC.
...CCC...`], ICON);
  def('i_tree', { c: RAMP.ice, k: P.navy }, [`
....c....
...ccc...
....k....
.c..k..c.
ccc.k.ccc
.k..k..k.
..kkkkk..
....k....
...ccc...`], ICON);
  def('i_map', { p: RAMP.sand, r: P.red, k: P.bark }, [`
ppp.ppp.p
ppkkppkpp
pkppkppkp
ppppprrpp
pkkpprrpp
ppppkppkp
pkppppkpp
ppp.ppp.p
.........`], ICON);
  def('i_book', { b: RAMP.red, p: P.cream, g: P.amber }, [`
.bbbbbbb.
bbbbbbbbp
bbbgggbbp
bbbgbbbbp
bbbgggbbp
bbbbbbbbp
bbbbbbbbp
bbbbbbbbp
.ppppppp.`], ICON);
  def('i_pet', { p: RAMP.brown }, [`
.p.....p.
ppp...ppp
.p..p..p.
...ppp...
..ppppp..
.ppppppp.
.ppppppp.
..ppppp..
.........`], ICON);
  def('i_exp', { c: RAMP.ice, w: P.white }, [`
....c....
...ccc...
..ccwcc..
.ccwwwcc.
ccccwcccc
.ccccccc.
..ccccc..
...ccc...
....c....`], ICON);
  def('i_chest', { w: RAMP.wood, m: RAMP.steel, g: P.amber }, [`
.........
.wwwwwww.
wwwwwwwww
mmmmmmmmm
wwwwgwwww
wwwwgwwww
mwwwwwwwm
mmmmmmmmm
.........`], ICON);
  def('i_bag', { b: RAMP.brown, s: P.bark }, [`
...bbb...
....s....
..bbbbb..
.bbbbbbb.
bbbbbbbbb
bbbbbbbbb
bbbbbbbbb
.bbbbbbb.
.........`], ICON);
  def('i_wanted9', { p: RAMP.sand, k: P.bark, r: P.red }, [`
ppppppppp
pkkpkpkkp
ppppppppp
ppkkkkkpp
pkkpkpkkp
ppkkkkkpp
ppppppppp
prrrrrrrp
ppppppppp`], ICON);

  // the staff's summoned hydra (three fire heads)
  def('hydra', { g: RAMP.fire, k: P.ink, y: P.yellow }, [`
..gg....gg....
.gkgg..gkgg.gg
.gggg..gggggkg
...gg...gg.ggg
....gg..gg.gg.
.....ggggggg..
.....yggggy...
....ggggggggg.
...ggggggggggg`], { ox: 7, oy: 8 });
  // ---------------- projectiles (pointing right) ----------------
  def('p_arrow', { f: P.red, s: P.cream, m: RAMP.silver }, [`
f........
fsssssssm
f........`], { ox: 4, oy: 1 });
  def('p_bolt', { f: P.amber, s: P.tan, m: RAMP.steel }, [`
.........m
ffsssssmmm
.........m`], { ox: 5, oy: 1 });
  def('p_magic', { o: P.orange, W: P.white }, [`
.oo.
oWWo
oWWo
.oo.`], { ox: 2, oy: 2 });
  VARIANTS.p_magic = { fire: { o: P.orange }, ice: { o: P.cyan }, light: { o: P.yellow }, poison: { o: P.green }, holy: { o: P.cream }, phys: { o: P.mist } };
  def('p_hatchet', { m: RAMP.silver, b: RAMP.wood }, [`
.mm..
mmmb.
.mb..
..b..`, `
.....
..mm.
.bmmm
b..m.`], { ox: 2, oy: 2 });
  def('p_bomb', { b: RAMP.ink, f: P.orange, y: P.yellow }, [`
...y.
..f..
.bbb.
bbbbb
bbbbb
.bbb.`], { ox: 2, oy: 3 });
  def('p_spore', { g: P.green, w: P.white }, [`
.g.g.
g.w.g
.g.g.`], { outline: false, ox: 2, oy: 1 });
  def('p_venom', { g: RAMP.green }, [`
..gg..
gggggg
..gg..`], { ox: 3, oy: 1 });
  def('p_curse', { p: RAMP.purple, k: P.ink }, [`
.ppp.
pkpkp
ppppp
.p.p.`], { ox: 2, oy: 2 });
  def('p_snowball', { s: RAMP.cloud }, [`
.sss.
sssss
sssss
.sss.`], { ox: 2, oy: 2 });
  def('p_shard', { c: RAMP.ice }, [`
..cc..
cccccc
..cc..`], { ox: 3, oy: 1 });
  def('p_voidbolt', { v: P.magenta, w: P.pink }, [`
..vv..
vvwwvv
..vv..`], { ox: 3, oy: 1 });
  def('p_beam', { r: P.red, w: P.white }, [`
rrrrrrrrrr
wwwwwwwwww
rrrrrrrrrr`], { outline: false, ox: 5, oy: 1 });
  def('p_bombm', { b: RAMP.ink, f: P.orange }, [`
..f.
.bbb
bbbb
.bb.`], { ox: 2, oy: 2 });
})();
