'use strict';
// =====================================================================
//  ART — every pixel sprite, authored as material masks.
//  Lowercase letters mapped to a ramp are auto-lit from the top-left
//  (rim light, core shadow, ground occlusion); the uppercase letter of
//  a ramp paints that material one shade darker by hand; letters mapped
//  to a single color are flat details (eyes, gems). Outlines are added
//  when baking. Pure data + math: the preview tool runs it in node.
// =====================================================================
const ART = (() => {
  const P = PAL;
  const RAMP = {
    green: [P.pine, P.moss, P.leaf, P.green, P.yellow],
    moss: [P.ink, P.pine, P.moss, P.leaf, P.green],
    blue: [P.night, P.navy, P.blue, P.cyan, P.white],
    ice: [P.navy, P.blue, P.cyan, P.white, P.white],
    red: [P.soil, P.wine, P.red, P.pink, P.cream],
    fire: [P.soil, P.rust, P.orange, P.amber, P.yellow],
    brown: [P.soil, P.bark, P.brown, P.tan, P.cream],
    wood: [P.ink, P.soil, P.bark, P.brown, P.tan],
    sand: [P.bark, P.brown, P.tan, P.cream, P.white],
    steel: [P.night, P.dusk, P.slate, P.steel, P.mist],
    silver: [P.dusk, P.slate, P.steel, P.mist, P.white],
    purple: [P.ink, P.plum, P.magenta, P.pink, P.cream],
    skin: [P.bark, P.skin2, P.skin, P.cream, P.white],
    gold: [P.bark, P.rust, P.amber, P.yellow, P.white],
    navy: [P.ink, P.night, P.dusk, P.slate, P.steel],
    bone: [P.slate, P.steel, P.mist, P.cream, P.white],
    dark: [P.ink, P.ink, P.soil, P.bark, P.brown],
    ghost: [P.dusk, P.steel, P.mist, P.white, P.white],
    cloud: [P.steel, P.mist, P.white, P.white, P.white],
    lava: [P.wine, P.rust, P.orange, P.amber, P.yellow],
    ink: [P.ink, P.ink, P.night, P.dusk, P.slate],
    teal: [P.ink, P.pine, P.moss, P.blue, P.cyan],
  };
  const S = {};
  // def(name, palette, [frame strings], { ox, oy, outline, shade })
  function def(name, pal, frames, o = {}) {
    const fr = frames.map(f => (Array.isArray(f) ? f : f.split('\n').map(r => r.trim()).filter(r => r.length)));
    const w = fr[0][0].length, h = fr[0].length;
    for (const f of fr) for (const r of f) if (r.length !== w || f.length !== h) throw new Error(`sprite ${name}: row "${r}" is ${r.length} wide, expected ${w}×${h}`);
    S[name] = { name, pal, frames: fr, w, h, ox: o.ox ?? Math.floor(w / 2), oy: o.oy ?? h - 1, outline: o.outline !== false, shade: o.shade !== false, o };
    return S[name];
  }
  const hex = h => { const n = parseInt(h.slice(1), 16); return [(n >> 16) & 255, (n >> 8) & 255, n & 255]; };

  // resolve one frame to RGBA with lighting and outline; palette overrides swap ramps
  function grid(name, fi = 0, over) {
    const sp = S[name];
    if (!sp) throw new Error('no sprite ' + name);
    const pal = over ? { ...sp.pal, ...over } : sp.pal;
    const rows = sp.frames[fi % sp.frames.length];
    return bake(rows, pal, sp);
  }
  function bake(rows, pal, sp = {}) {
    const h = rows.length, w = rows[0].length, pad = sp.outline === false ? 0 : 1;
    const W2 = w + pad * 2, H2 = h + pad * 2, px = new Uint8ClampedArray(W2 * H2 * 4);
    const at = (x, y) => (x < 0 || y < 0 || x >= w || y >= h ? '.' : rows[y][x]);
    const isRamp = ch => Array.isArray(pal[ch]);
    const mat = ch => (ch === '.' ? null : isRamp(ch) ? ch : pal[ch] === undefined && isRamp(ch.toLowerCase()) ? ch.toLowerCase() : '=' );
    // material bounding rows for the ground-occlusion gradient
    const box = {};
    for (let y = 0; y < h; y++) for (let x = 0; x < w; x++) {
      const m = mat(at(x, y)); if (!m || m === '=') continue;
      const b = box[m] || (box[m] = [y, y]); b[0] = Math.min(b[0], y); b[1] = Math.max(b[1], y);
    }
    for (let y = 0; y < h; y++) for (let x = 0; x < w; x++) {
      const ch = at(x, y); if (ch === '.') continue;
      let color;
      if (typeof pal[ch] === 'string') color = pal[ch];
      else {
        const m = mat(ch);
        if (!m || m === '=') throw new Error(`sprite ${sp.name}: letter "${ch}" has no color`);
        const ramp = pal[m];
        let v;
        if (ch !== m) v = 1;
        else if (sp.shade === false) v = 2;
        else {
          // a neighbour counts as "inside" when it is this material or a flat detail drawn on it
          const inside = (xx, yy) => { const c = at(xx, yy); if (c === '.') return false; const mm = mat(c); return mm === m || (mm === '=' && typeof pal[c] === 'string'); };
          const sky = (xx, yy) => at(xx, yy) === '.';
          const lit = sky(x, y - 1) || sky(x - 1, y);
          const shadow = !inside(x + 1, y) || !inside(x, y + 1);
          const under = !inside(x, y - 1) && !sky(x, y - 1); // another material sits on top
          v = 2;
          if (lit && !shadow) v = 3; else if (shadow && !lit) v = 1;
          if (under && v > 1) v = 1;
          const b = box[m], t = b[1] > b[0] ? (y - b[0]) / (b[1] - b[0]) : 0.5;
          if (b[1] - b[0] >= 5) { if (t > 0.72 && v >= 2 && !lit) v--; else if (t < 0.2 && v === 2) v = 3; }
        }
        color = ramp[clamp(v, 0, ramp.length - 1)];
      }
      const c = hex(color), i = ((y + pad) * W2 + x + pad) * 4;
      px[i] = c[0]; px[i + 1] = c[1]; px[i + 2] = c[2]; px[i + 3] = 255;
    }
    if (pad) {
      const oc = hex(sp.o?.outlineColor || P.ink), solid = new Uint8Array(W2 * H2);
      for (let i = 0; i < W2 * H2; i++) solid[i] = px[i * 4 + 3] ? 1 : 0;
      for (let y = 0; y < H2; y++) for (let x = 0; x < W2; x++) {
        const i = y * W2 + x; if (solid[i]) continue;
        if ((x > 0 && solid[i - 1]) || (x < W2 - 1 && solid[i + 1]) || (y > 0 && solid[i - W2]) || (y < H2 - 1 && solid[i + W2])) {
          px[i * 4] = oc[0]; px[i * 4 + 1] = oc[1]; px[i * 4 + 2] = oc[2]; px[i * 4 + 3] = 255;
        }
      }
    }
    return { w: W2, h: H2, px, ox: (sp.ox ?? 0) + pad, oy: (sp.oy ?? 0) + pad };
  }

  // ---------------------------------------------------------------
  //  THE HUNTER — upper body, legs and arm are separate layers so
  //  every pose shares the same design; coat ramp follows the armor
  // ---------------------------------------------------------------
  // 洛恩: silver hair, wide-brim hat, scarf pulled up to the eyes
  // 希娅: high golden ponytail with a red ribbon, teal half-cape
  const HERO_PAL = { h: RAMP.brown, q: RAMP.red, s: RAMP.skin, a: RAMP.silver, r: RAMP.red, c: RAMP.navy, b: RAMP.wood, g: P.amber, n: RAMP.navy, o: RAMP.wood, k: P.ink, e: P.ink, y: RAMP.gold, v: RAMP.teal, i: P.blue };
  // coat ramp follows the chest armor's material tier group (g0..g6)
  const COATS = { none: RAMP.navy, g0: RAMP.brown, g1: RAMP.steel, g2: RAMP.silver, g3: RAMP.red, g4: RAMP.teal, g5: RAMP.purple, g6: RAMP.gold };
  const HERO_UPPER = {
    m: [
      '........hhh.............',
      '.......hhhhh............',
      '.......hhhhhh...........',
      '.......hhhhhhh..........',
      '.......qqqqqqq..........',
      '...hhhhhhhhhhhhhhh......',
      '....HHHHHHHHHHHHH.......',
      '.......aasssss..........',
      '.......aassses..........',
      '........aassss..........',
      '........rrrrrr..........',
      '.......rrrrrrr..........',
      '....rrrrrrrrrr..........',
      '..rr...ccccbcc..........',
      '.......cccbccc..........',
      '.......ccbcccc..........',
      '.......bbbgbbb..........',
      '......ccccccccc.........',
      '......cccc..cccc........',
    ],
    f: [
      '........................',
      '.........yyyy...........',
      '........yyyyyy..........',
      '.......yyyyyyyy.........',
      '.....rryyyyyyyy.........',
      '.......yyyyyyyy.........',
      '.......yyyyysss.........',
      '.......yyysssss.........',
      '.......yysssis..........',
      '........ysssss..........',
      '........yySss...........',
      '.......vvvvvvv..........',
      '......vvvvvvvvv.........',
      '.....vvvccccbcvv........',
      '.....vv.cccbccc.........',
      '......v.ccbcccc.........',
      '........bbgbbb..........',
      '.......ccccccc..........',
      '......ccccccccc.........',
    ],
  };
  // flowing scarf tail (洛恩) / ponytail (希娅), three sway frames
  const HERO_TAIL = {
    m: [
      { 12: [[4, 'r'], [5, 'r']], 13: [[2, 'r'], [3, 'r']] },
      { 12: [[4, 'r'], [5, 'r']], 13: [[1, 'r'], [2, 'r'], [3, '.']], 11: [[6, 'r']] },
      { 12: [[3, 'r'], [4, 'r'], [5, 'r']], 13: [[2, '.'], [3, '.']], 11: [[2, 'r'], [6, 'r']] },
    ],
    f: [
      { 5: [[3, 'y'], [4, 'y'], [5, 'y'], [6, 'y']], 6: [[2, 'y'], [3, 'y'], [4, 'y']], 7: [[1, 'y'], [2, 'y'], [3, 'y']], 8: [[1, 'y'], [2, 'y']], 9: [[0, 'y'], [1, 'y']], 10: [[0, 'y']] },
      { 5: [[3, 'y'], [4, 'y'], [5, 'y'], [6, 'y']], 6: [[2, 'y'], [3, 'y'], [4, 'y']], 7: [[2, 'y'], [3, 'y']], 8: [[1, 'y'], [2, 'y']], 9: [[1, 'y'], [2, 'y']], 10: [[1, 'y']], 11: [[1, 'y']] },
      { 4: [[1, 'y'], [2, 'y']], 5: [[0, 'y'], [1, 'y'], [2, 'y'], [3, 'y'], [4, 'y'], [5, 'y'], [6, 'y']], 6: [[0, 'y'], [1, 'y'], [2, 'y'], [3, 'y'], [4, 'y']], 7: [[0, 'y'], [1, 'y']] },
    ],
  };
  const HERO_LEGS = {
    stand: ['.......NNN..nnn.........', '.......NNN..nnn.........', '.......NNN..nnn.........', '......OOOO..oooo........', '......OOOO..ooooo.......'],
    run0: ['......NNN...nnn.........', '.....NNN.....nnn........', '....NNN.......nnn.......', '...OOOO.......oooo......', '...OOO........ooooo.....'],
    run1: ['.......NNnnn............', '.......NNnnn............', '......OOO.nnn...........', '.....OOO..oooo..........', '..........ooooo.........'],
    run2: ['......nnn...NNN.........', '.....nnn.....NNN........', '....nnn.......NNN.......', '...oooo.......OOOO......', '...ooo........OOOOO.....'],
    run3: ['.......nnNNN............', '.......nnNNN............', '.......nnn..OOO.........', '......oooo...OOO........', '......ooooo.............'],
  };
  // arm layer: [x, y, letter]; hand = where the weapon grip sits
  const HERO_ARMS = {
    rest: { px: [[13, 13, 'c'], [14, 13, 'c'], [14, 14, 'c'], [15, 14, 'c'], [15, 15, 's'], [16, 15, 's']], hand: [16, 15] },
    raise: { px: [[13, 12, 'c'], [14, 12, 'c'], [14, 11, 'c'], [15, 11, 'c'], [15, 10, 's'], [16, 10, 's']], hand: [15, 10] },
    strike: { px: [[13, 13, 'c'], [14, 13, 'c'], [15, 13, 'c'], [16, 13, 'c'], [17, 13, 's'], [18, 13, 's']], hand: [18, 13] },
    cast: { px: [[13, 12, 'c'], [14, 11, 'c'], [15, 10, 'c'], [16, 9, 's'], [17, 9, 's']], hand: [17, 9] },
  };
  const HERO_DOWN = {
    m: [
      '........................',
      '................hhh.....',
      '...............hhhhh....',
      '.............qqhhhhhhh..',
      '..OO.NNnnccccrrsss......',
      '..OOnnnnccbcrrssse......',
      '..ooo.nnnccccrraa.......',
    ],
    f: [
      '........................',
      '........................',
      '........................',
      '.................yyy....',
      '..OO.NNnnccccvvsssyyyy..',
      '..OOnnnnccbcvvsssiyyy.yy',
      '..ooo.nnnccccvvyyyy...y.',
    ],
  };
  // pose = { legs, arm, bob, dx, scarf }
  function heroRows(pose, sex = 'm') {
    const W = 24, H = 24, rows = Array.from({ length: H }, () => '.'.repeat(W).split(''));
    const put = (x, y, c) => { if (x >= 0 && y >= 0 && x < W && y < H && c !== '.') rows[y][x] = c; };
    if (pose.down) {
      HERO_DOWN[sex].forEach((r, y) => [...r].forEach((c, x) => put(x, y + 17, c)));
      return rows.map(r => r.join(''));
    }
    const legs = HERO_LEGS[pose.legs || 'stand'];
    legs.forEach((r, y) => [...r].forEach((c, x) => put(x, 19 + y, c)));
    const by = pose.bob || 0, bx = pose.dx || 0;
    HERO_UPPER[sex].forEach((r, y) => [...r].forEach((c, x) => put(x + bx, y + by, c)));
    const sc = HERO_TAIL[sex][pose.scarf || 0];
    for (const y in sc) for (const [x, c] of sc[y]) { const yy = +y + by; if (c === '.') { if (rows[yy] && /[ry]/.test(rows[yy][x + bx])) rows[yy][x + bx] = '.'; } else put(x + bx, yy, c); }
    const arm = HERO_ARMS[pose.arm || 'rest'];
    for (const [x, y, c] of arm.px) put(x + bx, y + by, c);
    return rows.map(r => r.join(''));
  }
  const HERO_POSES = {
    idle0: { legs: 'stand', arm: 'rest' }, idle1: { legs: 'stand', arm: 'rest', bob: 1, scarf: 1 },
    run0: { legs: 'run0', arm: 'rest', scarf: 1 }, run1: { legs: 'run1', arm: 'rest', bob: -1, scarf: 2 },
    run2: { legs: 'run2', arm: 'rest', scarf: 1 }, run3: { legs: 'run3', arm: 'rest', bob: -1, scarf: 2 },
    raise: { legs: 'stand', arm: 'raise', dx: -1, scarf: 1 }, strike: { legs: 'run0', arm: 'strike', dx: 1, bob: 1, scarf: 2 },
    cast: { legs: 'stand', arm: 'cast', scarf: 2 }, hurt: { legs: 'stand', arm: 'rest', dx: -1, scarf: 2 }, down: { down: true },
    aim: { legs: 'stand', arm: 'strike', scarf: 1 }, loose: { legs: 'stand', arm: 'strike', dx: -1, scarf: 2 },
  };
  function heroGrid(poseName, coat = 'none', sex = 'm') {
    const pose = HERO_POSES[poseName];
    const rows = heroRows(pose, sex);
    const pal = { ...HERO_PAL, c: COATS[coat] || COATS.none };
    const g = bake(rows, pal, { name: 'hero:' + poseName, ox: 10, oy: 23 });
    const arm = HERO_ARMS[pose.arm || 'rest'];
    g.hand = [arm.hand[0] + (pose.dx || 0) + 1, arm.hand[1] + (pose.bob || 0) + 1];
    return g;
  }

  // ---------------------------------------------------------------
  //  WEAPONS — drawn pointing up-right; 90° turns are lossless
  //  grip = where the hand holds it. Blade ramp follows rarity.
  // ---------------------------------------------------------------
  const BLADE = [RAMP.silver, RAMP.silver, RAMP.ice, RAMP.purple, RAMP.gold];
  const GEM = [P.steel, P.green, P.cyan, P.pink, P.red];
  const WEAPON_PAL = { m: RAMP.silver, b: RAMP.wood, g: RAMP.gold, e: P.red };
  def('w_sword', WEAPON_PAL, [`
...............m
..............mm
.............mm.
............mm..
...........mm...
..........mm....
.........mm.....
........mm......
.......mm.......
..g...mm........
...g.mm.........
....gm..........
...b.g..........
..b...g.........
.g..............
................`], { ox: 0, oy: 0 });
  def('w_dagger', WEAPON_PAL, [`
................
................
................
...........m....
..........mm....
.........mm.....
........mm......
.......mm.......
..g...mm........
...g.mm.........
....gm..........
...b.g..........
..b...g.........
.g..............
................
................`], { ox: 0, oy: 0 });
  def('w_axe', WEAPON_PAL, [`
...........mm...
..........bmmm..
.........b.mmmm.
........b..mmmmm
.......b....mmmm
......b......mm.
.....b..........
....b...........
...b............
..b.............
.b..............
b...............
................
................
................
................`], { ox: 0, oy: 0 });
  def('w_hammer', WEAPON_PAL, [`
.........m......
........mmm.....
.......mmmmm....
......mmmmmmm...
.......mmmmmmm..
........mmmmm...
.......b.mmm....
......b...m.....
.....b..........
....b...........
...b............
..b.............
.b..............
g...............
................
................`], { ox: 0, oy: 0 });
  def('w_spear', WEAPON_PAL, [`
.............mm.
............mmmm
............mmm.
...........gmm..
..........b.....
.........b......
........b.......
.......b........
......b.........
.....b..........
....b...........
...b............
..b.............
.b..............
b...............
................`], { ox: 0, oy: 0 });
  const GRIP = { w_sword: [3, 12], w_dagger: [3, 11], w_axe: [3, 8], w_hammer: [4, 9], w_spear: [6, 8] };

  // ---------------------------------------------------------------
  //  MONSTERS — authored facing left (toward the hunter)
  // ---------------------------------------------------------------
  def('slime', { a: RAMP.green, k: P.ink, w: P.white }, [`
................
.....aaaaaa.....
...aaaaaaaaaa...
..aawwaaaaaaaa..
.aawwaaaaaaaaaa.
.awaaaaaaaaaaaa.
.aakkaaaakkaaaa.
.aakkaaaakkaaaa.
.aaaaakkaaaaaaa.
.aaaaaaaaaaaaaa.
..aaaaaaaaaaaa..`, `
................
................
....aaaaaaaa....
..aaaaaaaaaaaa..
.aawwaaaaaaaaaa.
aawwaaaaaaaaaaaa
aakkaaaakkaaaaaa
aakkaaaakkaaaaaa
aaaaaakkaaaaaaaa
aaaaaaaaaaaaaaaa
.aaaaaaaaaaaaaa.`]);
  def('rabbit', { f: RAMP.sand, e: RAMP.bone, h: RAMP.bone, q: P.pink, p: P.pink, k: P.ink }, [`
......ff.ff.....
......fq.fqf....
......fq.fqf....
..h...fqffqf....
...h..fffff.....
....hffffff.....
..ffffkfffff....
.pfffffffffffff.
..eeffffffffffff
..eeefffffffffff
...eefffffffffF.
...ff.ff..FfffF.
..fff.fff.FFff..`]);
  def('shroom', { r: RAMP.red, c: P.cream, s: RAMP.bone, k: P.ink, m: P.ink, f: RAMP.brown }, [`
.....rrrrrr.....
...rrccrrrrrr...
..rrcccrrrrccrr.
.rrrrcrrrrrrcrrr
.rrrrrrrcccrrrrr
rrcrrrrrcccrrrrr
rcccrrrrrrrrrrrr
.RRRRRRRRRRRRRR.
....ssssssss....
...sksssksss....
...sssssssss....
...ssmmmssss....
....sssssss.....
...ff.....ff....`]);
  def('wasp', { y: RAMP.gold, h: RAMP.ink, v: RAMP.ghost, k: P.ink, r: P.red }, [`
......vv.vv...
.....vvv.vvv..
......vv.vvv..
..yy...v.v....
.yyyy.hhy.....
.ryyyhhhykyky.
.yyyyhhkyykyyk
..yy.hhkyykyy.
.....h..h.....`, `
..............
..............
.....vvv.vvv..
..yy.vvvvvvvv.
.yyyy.hhy.....
.ryyyhhhykyky.
.yyyyhhkyykyyk
..yy.hhkyykyy.
.....h..h.....`]);
  def('bat', { b: RAMP.purple, v: RAMP.purple, e: P.yellow }, [`
.v............v.
.vv..........vv.
.vvv..b..b..vvv.
.vvvvbbbbbbvvvv.
..vvvbebebbvvv..
...vvbbbbbbvv...
....v.bbbb.v....
.......bb.......`, `
................
................
......b..b......
.....bbbbbb.....
..vvvbebebbvvv..
.vvvvbbbbbbvvvv.
vvvv..bbbb..vvvv
vv.....bb.....vv`]);
  def('goblin', { g: RAMP.green, t: RAMP.moss, c: RAMP.wood, y: P.yellow, k: P.ink, w: P.white }, [`
....................
.cc.................
cccc.....gggg.......
cccc....gggggg......
.cc....gggggggggg.gg
..c...ggggggggggggg.
..c..gyykggggggggg..
..c.ggggggggggggg...
..cgggwgwgggggg.....
..gg..ggggggggg.....
...ggtttttttttt.....
.....ttttttttttgg...
.....ttttttttttt.g..
.....tTtTtTtTtt.....
......gg....gg......
.....ggg....ggg.....`, `
....................
....................
.........gggg.......
........gggggg......
.......gggggggggg.gg
......ggggggggggggg.
.....gyykggggggggg..
....ggggggggggggg...
....ggwgwgggggg.....
cccc..ggggggggg.....
ccccgtttttttttt.....
.....ttttttttttgg...
.....ttttttttttt.g..
.....tTtTtTtTtt.....
......gg....gg......
.....ggg....ggg.....`]);
  def('scorpion', { s: RAMP.fire, w: P.cream, e: P.ink }, [`
......................
..............ssss....
.............ss..ss...
............ww....ss..
..................ss..
.................sss..
................sss...
.SS..........ssss.....
SssS..sssssssssss.....
.ssssssssssssssss.....
SssS.essssssssss......
.SS..s.s.s.s.s.s......`, `
......................
...............sss....
.............sss.ss...
...........ww.....ss..
..................ss..
.................sss..
................sss...
SS...........ssss.....
sSsS..sssssssssss.....
..sssssssssssssss.....
sSsS.essssssssss......
SS....s.s.s.s.s.s.....`]);
  def('mummy', { b: RAMP.bone, e: P.cyan, k: P.ink }, [`
......bbbb......
.....bbbbbb.....
.....BbbbbB.....
....bebbbbbb....
.....bbBbbbb....
......bbbb......
bbbbbbbbbbbb....
BbbbBbbbbbbbb...
......bbbBbbb...
......bbbbbbb...
......bBbbbbb...
......bbbbbBb...
......bbbbbbb...
......bbb.bbb...
......bbb.bbb...
.....bbbb.bbbb..`, `
......bbbb......
.....bbbbbb.....
.....BbbbbB.....
....bebbbbbb....
.....bbBbbbb....
......bbbb......
.bbbbbbbbbbb....
bBbbbBbbbbbbb...
......bbbBbbb...
......bbbbbbb...
......bBbbbbb...
......bbbbbBb...
......bbbbbbb...
......bbb.bbb...
.....bbbb.bbb...
.........bbbb...`]);
  def('cactus', { c: RAMP.green, p: P.pink, y: P.yellow, w: P.cream, k: P.ink, m: P.wine, d: RAMP.brown }, [`
.......pp.......
......pyyp......
.......pp.......
.....cccccc.....
....cccccccc....
....cwcccwcc....
.cc.ckcccckc.cc.
.cc.cccccccc.cc.
.ccccccmmccccc..
..cccccccccccc..
....cwcccccwc...
....cccccccc....
....cccwcccc....
....cccccccc....
...dddddddddd...
..dddddddddddd..`]);
  def('wolf', { f: RAMP.ghost, e: P.cyan, k: P.ink, w: P.white }, [`
..........................
.....ff...................
....fff...................
...ffffff.................
.ffffeffff..............ff
kffffffffffff.........fff.
.fffffffffffffffffffffff..
..wwffffffffffffffffffff..
....fffffffffffffffffff...
.....fffffffffffffffff....
.....FFf.FFf.....ffF.ffF..
.....ff..ff......ff..ff...
....fff.fff.....fff.fff...`, `
..........................
.....ff...................
....fff...................
...ffffff.................
.ffffeffff.............ff.
kffffffffffff........fff..
.fffffffffffffffffffffff..
..wwffffffffffffffffffff..
....fffffffffffffffffff...
.....fffffffffffffffff....
......FFfFFf......ffFffF..
.....ff....ff....ff....ff.
....fff...fff...fff...fff.`]);
  def('yeti', { f: RAMP.cloud, s: RAMP.ice, e: P.ink, m: P.ink, t: P.white }, [`
........................
........ffffff..........
......ffffffffff........
.....ffffffffffff.......
....fffssssssffff.......
....ffsessesssfff.......
...fffssssssssffff......
...fffsmtmtmssfffff.....
..ffffsssssssffffff.....
.fffffffffffffffffff....
ffffffffffffffffffffff..
fff.fffffffffffffff.fff.
fff.fffffffffffffff.fff.
.ff..ffffffffffffff..ff.
.....fffffffffffff......
.....fffff...fffff......
.....ffff.....ffff......
....fffff.....fffff.....`, `
........................
........ffffff..........
......ffffffffff........
.....ffffffffffff.......
....fffssssssffff.......
....ffsessesssfff.......
...fffssssssssffff......
...fffsmmmmmssfffff.....
..ffffsssssssffffff.....
.fffffffffffffffffff....
ffffffffffffffffffffff..
fff.fffffffffffffff.fff.
.ff.fffffffffffffff.ff..
.....ffffffffffffff.....
.....fffffffffffff......
.....fffff...fffff......
......ffff...ffff.......
.....fffff...fffff......`]);
  def('imp', { r: RAMP.red, w: RAMP.purple, h: RAMP.bone, e: P.yellow, m: P.ink }, [`
...h....h.......
...hrrrrh.......
...rrrrrr.ww....
..rerrerrwwww...
..rrrrrrrwwwww..
...rmmrrwwwwww..
....rrrrr.wwww..
...rrrrrrr..ww..
..r.rrrrr.......
.....r..r.rr....
....rr..rr..r...`, `
...h....h.......
...hrrrrh.......
...rrrrrr.......
..rerrerrw......
..rrrrrrrwww....
...rmmrrwwwwww..
....rrrrrwwwwwww
...rrrrrrr.wwww.
..r.rrrrr...ww..
.....r..r.rr....
....rr..rr..r...`]);
  def('salamander', { s: RAMP.fire, b: RAMP.sand, y: P.yellow, o: P.orange, e: P.yellow, k: P.ink }, [`
............................
..........y.....y...........
.........yoy...yoy..........
...sssssssssssssssss........
.ssksssssssssssssssssss.....
ssssssssssssssssssssssssss..
.bbbbbbbbbbbbssssssssssssssy
...ss..ss......ss...ss....yo
..ss...ss.....ss...ss.......`, `
............................
.........y.....y............
........yoy...yoy...........
...sssssssssssssssss........
.ssksssssssssssssssssss.....
ssssssssssssssssssssssssss..
.bbbbbbbbbbbbsssssssssssssy.
....ss.ss.......ss.ss....yo.
...ss...ss.....ss...ss......`]);
  def('ghost', { g: RAMP.ghost, e: P.ink, m: P.ink }, [`
.....gggggg.....
....gggggggg....
...gggggggggg...
..ggeeggeegggg..
..ggeeggeegggg..
..gggggggggggg..
..ggggmmgggggg..
.gggggggggggggg.
ggggggggggggggg.
.gggggggggggggg.
.ggggggggggggg..
..gg.ggg.ggg.g..
..g...g...g.....`, `
.....gggggg.....
....gggggggg....
...gggggggggg...
..ggeeggeegggg..
..ggeeggeegggg..
..gggggggggggg..
..ggggmmgggggg..
.gggggggggggggg.
.ggggggggggggggg
.gggggggggggggg.
..ggggggggggggg.
..g.ggg.ggg.gg..
....g...g...g...`]);
  def('zombie', { z: RAMP.moss, c: RAMP.steel, e: P.red, k: P.ink }, [`
......zzzz......
.....zzzzzz.....
.....zezzzz.....
.....zzzzzz.....
......zkkz......
.......zz.......
zzzzzcccccc.....
ZzzzccccccCc....
......cccccc....
......cCcccc....
......cccccC....
......cccccc....
......cc.ccc....
......cc..cc....
......zz..zz....
.....zzz.zzz....`, `
......zzzz......
.....zzzzzz.....
.....zezzzz.....
.....zzzzzz.....
......zkkz......
.......zz.......
.zzzzcccccc.....
zZzzccccccCc....
......cccccc....
......cCcccc....
......cccccC....
......cccccc....
......cc.ccc....
......cc..cc....
.....zz...zz....
.....zz..zzz....`]);
  def('wisp', { w: RAMP.ice, k: P.ink }, [`
......w.....
.....ww.....
....www.w...
....wwwww...
...wwwwwww..
..wwwwwwww..
..wkwwkwww..
..wwwwwwww..
...wwwwww...
....wwww....`, `
.....w......
.....ww..w..
....wwwwww..
...wwwwww...
...wwwwwww..
..wwwwwwww..
..wkwwkwww..
..wwwwwwww..
...wwwwww...
....wwww....`]);
  def('golem', { r: RAMP.steel, c: RAMP.purple, e: P.cyan }, [`
..........................
.............c............
............cc.c..........
.....rrrr..ccc.cc.........
....rrrrrr.cccccc.........
...rrrrrrrrrrrrrrr........
...rerrerrrrrrrrrrr.......
...rrrrrrrrrrrrrrrrr......
rrrrrrrrrrrrrrrrrrrrrr....
rrrr.rrrrrrrrrrrrr.rrrr...
rrr..rrrrrrrrrrrrr..rrr...
.rr..rrrrrrrrrrrrr..rr....
.....rrrrrr..rrrrr........
.....rrrrr....rrrr........
....rrrrrr....rrrrr.......`]);
  def('mole', { m: RAMP.wood, h: RAMP.gold, l: P.yellow, n: P.pink, c: RAMP.bone, k: P.ink }, [`
......hhhhh.........
.....hhhhhhh........
....lhhhhhhhh.......
....mmmmmmmmmm......
...mmkmmmmmmmmm.....
.nmmmmmmmmmmmmmm....
..mmmmmmmmmmmmmmm...
...cmmmmmmmmmmmmm...
..ccmmmmmmmmmmmmm...
....mmmmmmmmmmmm....
.....mm......mm.....
....mmm.....mmm.....`]);
  def('harpy', { s: RAMP.skin, h: RAMP.purple, f: RAMP.sand, t: RAMP.bone, k: P.ink }, [`
..............ff........
............ffff....ff..
...hhh....fffff...fff...
..hhhhh..ffffff.ffff....
..hshhh.fffffffffff.....
..ksshh.ffffffffff......
...sshhfffffffff........
...sss.ffffffff.........
..sssssfffffff..........
...sssfffffff...........
....fffffff.............
.....fffff..............
.....t..t...............
....tt.tt...............`, `
........................
........................
...hhh..................
..hhhhh.................
..hshhh.ffff............
..ksshhffffffff.........
...sshhffffffffffff.....
...sss.fffffffffffffff..
..sssssffffffffff..fff..
...sssfffffff.......ff..
....fffffff.............
.....fffff..............
.....t..t...............
....tt.tt...............`]);
  def('hawk', { b: RAMP.navy, h: RAMP.silver, w: RAMP.steel, y: P.amber, e: P.yellow, t: P.amber, f: RAMP.navy }, [`
.............ww.......
............www.......
...........wwww.......
..........wwwww.......
.........wwwwww.......
..hhh...wwwwww........
yhhehhbbwwwwww........
.yyhhbbbbbbbbbbbbfff..
...hbbbbbbbbbbbbffff..
.....bbbbbbbbbb..ff...
......t...t...........
......................`, `
......................
......................
......................
......................
......................
..hhh.................
yhhehhbbbbbbbbbbb.....
.yyhhbbbwwwwwwwbbbfff.
...hbbbbwwwwwwwwbffff.
.....bbbbwwwwwwww.ff..
......t...twwwwww.....
............www.......`]);
  def('goldgob', { g: RAMP.green, s: RAMP.brown, y: P.yellow, e: P.yellow, k: P.ink, t: RAMP.moss }, [`
..........sss.......
........sssssss.....
.......sssssssss....
......sssyssyssss...
......sssssssssss...
..ggg.ssssyssssss...
.gggggsssssssssss...
.geggggssssssssss...
ggggggg.sssssss.....
.gggggggg...........
..ggtttt............
...tttttt...........
...gg..gg...........`]);
  // ---------------------------------------------------------------
  //  BOSSES — big masks laid down with shapes, then hand details
  // ---------------------------------------------------------------
  function Paint(w, h) {
    const g = Array.from({ length: h }, () => new Array(w).fill('.'));
    const set = (x, y, c) => { if (x >= 0 && y >= 0 && x < w && y < h) g[y][x] = c; };
    return {
      px(x, y, c) { set(Math.round(x), Math.round(y), c); return this; },
      dots(list, c) { for (const [x, y] of list) set(x, y, c); return this; },
      ell(cx, cy, rx, ry, c, keep) {
        for (let y = Math.floor(cy - ry - 1); y <= cy + ry + 1; y++) for (let x = Math.floor(cx - rx - 1); x <= cx + rx + 1; x++) {
          const dx = (x + 0.5 - cx) / rx, dy = (y + 0.5 - cy) / ry;
          if (dx * dx + dy * dy <= 1 && (!keep || keep(x, y))) set(x, y, c);
        }
        return this;
      },
      rect(x, y, rw, rh, c) { for (let j = y; j < y + rh; j++) for (let i = x; i < x + rw; i++) set(i, j, c); return this; },
      poly(pts, c) {
        let y0 = Infinity, y1 = -Infinity, x0 = Infinity, x1 = -Infinity;
        for (const [x, y] of pts) { y0 = Math.min(y0, y); y1 = Math.max(y1, y); x0 = Math.min(x0, x); x1 = Math.max(x1, x); }
        for (let y = Math.floor(y0); y <= y1; y++) for (let x = Math.floor(x0); x <= x1; x++) {
          const px = x + 0.5, py = y + 0.5; let inside = false;
          for (let i = 0, j = pts.length - 1; i < pts.length; j = i++) {
            const [xi, yi] = pts[i], [xj, yj] = pts[j];
            if ((yi > py) !== (yj > py) && px < (xj - xi) * (py - yi) / (yj - yi) + xi) inside = !inside;
          }
          if (inside) set(x, y, c);
        }
        return this;
      },
      line(ax, ay, bx, by, c, th = 1) {
        const r = th / 2 + 0.01, dx = bx - ax, dy = by - ay, L2 = dx * dx + dy * dy || 1;
        for (let y = Math.floor(Math.min(ay, by) - r - 1); y <= Math.max(ay, by) + r + 1; y++) for (let x = Math.floor(Math.min(ax, bx) - r - 1); x <= Math.max(ax, bx) + r + 1; x++) {
          const px = x + 0.5, py = y + 0.5;
          let t = ((px - ax - 0.5) * dx + (py - ay - 0.5) * dy) / L2; t = t < 0 ? 0 : t > 1 ? 1 : t;
          const ex = ax + 0.5 + dx * t - px, ey = ay + 0.5 + dy * t - py;
          if (ex * ex + ey * ey <= r * r) set(x, y, c);
        }
        return this;
      },
      path(pts, c, th) { for (let i = 1; i < pts.length; i++) this.line(pts[i - 1][0], pts[i - 1][1], pts[i][0], pts[i][1], c, th); return this; },
      clearBelow(y) { for (let j = y + 1; j < h; j++) g[j].fill('.'); return this; },
      rows() { return g.map(r => r.join('')); },
    };
  }

  function slimeKing(s) {
    const p = Paint(46, 36);
    p.ell(23, 29 + s, 20 + s, 20 - s * 2, 'a').clearBelow(33);
    p.ell(3, 31, 2, 2, 'a').ell(43, 30, 1.6, 1.6, 'a');
    const cy = 3 + s * 2;
    p.rect(15, cy + 3, 16, 6, 'c').rect(15, cy + 1, 3, 2, 'c').rect(21, cy - 1, 4, 4, 'c').rect(28, cy + 1, 3, 2, 'c');
    p.px(16, cy, 'c').px(22, cy - 2, 'c').px(23, cy - 2, 'c').px(29, cy, 'c');
    p.rect(15, cy + 8, 16, 1, 'C');
    p.dots([[17, cy + 5], [28, cy + 5]], 'r').rect(22, cy + 4, 2, 2, 'r').px(22, cy + 4, 'w');
    const ey = 18 + s;
    p.ell(12, ey, 3.2, 4, 'w').ell(24, ey, 3.2, 4, 'w');
    p.ell(11, ey + 1, 1.7, 2.4, 'k').ell(23, ey + 1, 1.7, 2.4, 'k').px(10, ey - 1, 'w').px(22, ey - 1, 'w');
    p.path([[8, 26 + s], [12, 28 + s], [18, 28 + s], [22, 26 + s]], 'k', 1).px(14, 29 + s, 'q').px(15, 29 + s, 'q');
    p.dots([[8, 14 + s], [7, 15 + s], [7, 16 + s], [9, 13 + s]], 'h');
    return p.rows();
  }
  def('b_slimeking', { a: RAMP.green, c: RAMP.gold, r: P.red, k: P.ink, w: P.white, q: P.pink, h: P.white }, [slimeKing(0), slimeKing(1)], { ox: 23, oy: 33 });

  function treant(s) {
    const p = Paint(44, 50);
    p.ell(22, 9 - s, 15, 8, 'l').ell(10, 14 - s, 8, 6, 'l').ell(34, 13 - s, 9, 7, 'l').ell(22, 4 - s, 9, 4, 'l');
    p.poly([[15, 12], [29, 12], [31, 40], [35, 47], [9, 47], [13, 40]], 'b');
    p.line(12, 44, 3, 49, 'b', 3).line(32, 44, 41, 49, 'b', 3).line(21, 45, 20, 49, 'b', 3);
    p.line(15, 24, 6, 30 + s, 'b', 4).line(6, 30 + s, 1, 26 + s, 'b', 2).line(6, 30 + s, 2, 34 + s, 'b', 2).line(6, 30 + s, 7, 35 + s, 'b', 2);
    p.line(29, 22, 38, 15 - s, 'b', 3).line(38, 15 - s, 41, 10 - s, 'b', 2).line(38, 15 - s, 43, 16 - s, 'b', 1);
    p.ell(10, 13 - s, 3, 2, 'L').ell(30, 7 - s, 4, 2, 'L').ell(36, 16 - s, 3, 2, 'L');
    p.line(15, 18, 28, 18, 'B', 1);
    p.ell(18, 21, 2.6, 2.2, 'k').ell(26, 21, 2.6, 2.2, 'k').px(17, 21, 'y').px(25, 21, 'y');
    p.rect(16, 27, 11, 4, 'k').dots([[17, 27], [19, 27], [21, 27], [23, 27], [25, 27], [18, 30], [20, 30], [22, 30], [24, 30]], 'B');
    p.line(20, 33, 20, 42, 'B', 1).line(25, 33, 26, 43, 'B', 1).line(15, 34, 16, 41, 'B', 1);
    p.ell(14, 37, 2, 1.5, 'm').ell(28, 26, 1.6, 1.2, 'm').ell(23, 44, 2.5, 1.2, 'm');
    p.rect(29, 34, 3, 1, 'r').rect(30, 33, 1, 1, 'r').px(30, 34, 'w').px(31, 35, 'B');
    return p.rows();
  }
  def('b_treant', { l: RAMP.moss, b: RAMP.wood, k: P.ink, y: P.yellow, m: P.green, r: P.red, w: P.white }, [treant(0), treant(1)], { ox: 22, oy: 49 });

  function scorpKing(s) {
    const p = Paint(54, 38);
    p.line(20, 32, 15, 37, 'S', 2).line(26, 33, 24, 37, 'S', 2).line(32, 33, 32, 37, 'S', 2).line(38, 32, 41, 37, 'S', 2);
    p.ell(7, 19 - s, 4, 3.5, 'S').line(0, 19 - s, 5, 19 - s, '.', 1).line(10, 22, 14, 25, 'S', 2);
    p.ell(30, 27, 15, 7, 's');
    p.line(24, 21, 24, 33, 'S', 1).line(30, 20, 30, 34, 'S', 1).line(36, 21, 36, 33, 'S', 1);
    p.ell(44, 22, 4, 4, 's').ell(47, 15, 4, 4, 's').ell(46, 8 + s, 4, 3.5, 's').ell(40, 4 + s, 4, 3, 's').ell(34, 5 + s, 3, 2.5, 's');
    p.poly([[32, 3 + s], [27, 7 + s], [33, 7 + s]], 'w');
    p.ell(15, 27, 7, 6, 's');
    p.line(12, 30, 6, 30, 's', 3).ell(5, 29 + s, 5, 4.5, 's').line(0, 29 + s, 4, 29 + s, '.', 1);
    p.dots([[11, 20], [13, 19], [15, 19], [17, 20], [12, 21], [16, 21], [14, 21]], 'g').dots([[13, 18], [15, 18]], 'g').px(14, 17, 'g');
    p.dots([[9, 25], [11, 24]], 'e');
    p.dots([[26, 22], [32, 21], [38, 22]], 'g');
    return p.rows();
  }
  def('b_scorpking', { s: RAMP.fire, g: RAMP.gold, w: RAMP.bone, e: P.red }, [scorpKing(0), scorpKing(1)], { ox: 27, oy: 37 });

  function wolfKing(s) {
    const p = Paint(54, 36);
    p.rect(18, 24, 4, 10 - s, 'F').rect(44, 23, 4, 11 - s, 'F');
    p.poly([[48, 16], [54, 7 - s], [53, 16], [50, 20]], 'f').poly([[52, 9 - s], [54, 5 - s], [54, 10 - s]], 'i');
    p.ell(32, 19, 17, 8, 'f').ell(16, 18, 9, 9, 'f');
    p.rect(12, 24, 4, 10 + s, 'f').rect(38, 24, 4, 10 + s, 'f').rect(11, 33 + s, 6, 2, 'f').rect(37, 33 + s, 6, 2, 'f');
    p.poly([[12, 3], [15, 7], [11, 7]], 'F').poly([[8, 1], [11, 6], [7, 6]], 'f');
    p.ell(9, 11, 7, 6, 'f').poly([[0, 13], [6, 9], [8, 15], [2, 16]], 'f');
    p.dots([[0, 13], [1, 13], [0, 12]], 'k').line(2, 16, 8, 15, 'k', 1).dots([[3, 17], [6, 16]], 'w');
    p.dots([[6, 10], [7, 10]], 'e').line(5, 7, 9, 12, 'r', 1).dots([[6, 10], [7, 10]], 'e');
    p.poly([[12, 6], [16, 0], [18, 8]], 'i').poly([[17, 8], [23, 2], [24, 11]], 'i').poly([[24, 11], [30, 5], [30, 13]], 'i').poly([[30, 12], [36, 8], [35, 14]], 'i');
    return p.rows();
  }
  def('b_wolfking', { f: RAMP.ghost, i: RAMP.ice, k: P.ink, w: P.white, e: P.cyan, r: P.red }, [wolfKing(0), wolfKing(1)], { ox: 27, oy: 35 });

  function magma(s) {
    const p = Paint(46, 48);
    p.rect(12, 36, 8, 12, 'r').rect(26, 36, 8, 12, 'r');
    p.line(40, 20, 43, 30, 'R', 5).ell(43, 33 + s, 4, 4, 'R');
    p.poly([[8, 14], [38, 14], [40, 22], [36, 38], [10, 38], [6, 22]], 'r');
    p.ell(7, 18, 6, 5, 'r').ell(39, 18, 6, 5, 'r');
    p.ell(23, 9 + s, 7, 6, 'r');
    p.line(6, 20, 4, 32, 'r', 6).ell(4, 35 - s, 5, 4.5, 'r');
    p.ell(23, 26, 5, 5, 'l').ell(23, 26, 2.2, 2.2, 'y');
    p.path([[12, 16], [14, 19], [16, 22]], 'o').path([[31, 16], [29, 19], [30, 22]], 'o').path([[14, 33], [17, 31], [19, 32]], 'o');
    p.path([[5, 26], [4, 29], [5, 31]], 'o').path([[16, 46], [15, 42], [17, 40]], 'o').path([[29, 44], [31, 41]], 'o').path([[36, 26], [34, 30]], 'o');
    p.dots([[19, 9 + s], [20, 9 + s], [25, 9 + s], [26, 9 + s]], 'y').dots([[21, 3 + s], [24, 3 + s]], 'o');
    return p.rows();
  }
  def('b_magma', { r: RAMP.navy, l: RAMP.lava, y: P.yellow, o: P.orange }, [magma(0), magma(1)], { ox: 23, oy: 47 });

  // 提灯女巫 — a young sorceress: silver hair, glowing eyes, purple gown, lantern staff
  function witch(s) {
    const p = Paint(40, 52);
    p.poly([[15, 11], [27, 11], [31, 20], [34, 33 + s], [31, 39 + s], [27, 31], [22, 24]], 'n');
    p.poly([[14, 25], [23, 25], [26, 31], [35, 47], [5, 47], [11, 31]], 'c');
    for (let x = 5; x < 35; x += 5) p.ell(x + 2.5, 47 + ((x / 5 + s) % 2), 2.6, 2, 'c');
    p.line(20, 32, 26, 46, 'C', 1).line(16, 32, 11, 46, 'C', 1).line(18, 33, 18, 46, 'C', 1);
    p.poly([[14, 24], [23, 24], [22, 30], [15, 30]], 'd').rect(13, 30, 12, 1, 'g').px(18, 27, 'q');
    p.rect(16, 21, 4, 4, 's');
    p.line(15, 26, 10, 31, 'c', 3).ell(9, 31, 1.8, 1.8, 's');
    p.ell(17, 17, 4.6, 5.2, 's');
    p.poly([[12, 11], [23, 11], [23, 15], [21, 14], [19, 16], [17, 14], [15, 16], [13, 15]], 'n');
    p.line(12, 13, 11, 27 + s, 'n', 2).line(22, 13, 23, 20, 'n', 1);
    p.dots([[13, 16], [14, 16], [15, 16], [17, 16], [18, 16], [19, 16]], 'k');
    p.dots([[14, 17], [15, 17], [18, 17], [19, 17]], 'e').dots([[14, 18], [15, 18], [18, 18], [19, 18]], 'i').dots([[14, 17], [18, 17]], 'W');
    p.dots([[13, 19], [20, 19]], 'p').px(16, 21, 'm');
    p.poly([[16, 0], [21, 1], [27, 9], [9, 9]], 'h').poly([[21, 0], [27, -1], [24, 3]], 'h');
    p.ell(18, 10, 14, 2.2, 'h').rect(11, 7, 15, 2, 'g').dots([[13, 4], [13, 5], [14, 6]], 'y');
    p.line(7, 10, 9, 50, 'w', 2);
    p.rect(3, 1 - s, 9, 10, 'g').rect(4, 2 - s, 7, 8, 'f').ell(7.5, 6 - s, 1.8, 2.2, 'W').line(7, -1 - s, 8, 1 - s, 'g', 1);
    return p.rows();
  }
  def('b_witch', { n: RAMP.silver, c: RAMP.purple, d: RAMP.navy, s: RAMP.skin, e: P.cyan, i: P.blue, k: P.ink, p: P.pink, m: P.red, q: P.cyan, h: RAMP.purple, g: RAMP.gold, w: RAMP.wood, f: RAMP.ice, W: P.white, y: P.yellow }, [witch(0), witch(1)], { ox: 20, oy: 50 });

  function spider(s) {
    const p = Paint(56, 34);
    const far = [[22, 19, 16, 11, 10, 32], [28, 20, 26, 11, 24, 32], [34, 20, 40, 11, 42, 32], [40, 19, 50, 11, 54, 32]];
    far.forEach(([a, b, c, d, e, f], i) => p.path([[a, b], [c, d + (i % 2 ? s : 0)], [e, f]], 'L', 1));
    p.ell(39, 17, 14, 10, 'b');
    p.poly([[31, 10], [35, 0], [38, 11]], 'c').poly([[39, 9], [44, 0], [46, 11]], 'q').poly([[45, 13], [53, 6], [50, 17]], 'c');
    p.line(29, 22, 49, 22, 'B', 1).line(31, 25, 46, 25, 'B', 1);
    p.ell(21, 21, 8, 6, 'b').ell(12, 22, 5, 4.5, 'b');
    const near = [[18, 22, 10, 9, 3, 33], [24, 23, 19, 10, 15, 33], [30, 23, 33, 10, 35, 33], [36, 22, 45, 9, 50, 33]];
    near.forEach(([a, b, c, d, e, f], i) => p.path([[a, b], [c, d - (i % 2 ? 0 : s)], [e, f]], 'l', 2));
    p.dots([[9, 20], [11, 19], [13, 19], [10, 22], [8, 22], [12, 21]], 'e');
    p.dots([[8, 26], [8, 27], [11, 26], [11, 27]], 'w');
    return p.rows();
  }
  def('b_spider', { b: RAMP.navy, l: RAMP.steel, c: RAMP.ice, q: RAMP.purple, e: P.red, w: P.cream }, [spider(0), spider(1)], { ox: 28, oy: 33 });

  function griffin(s) {
    const p = Paint(54, 46);
    p.poly([[26, 22], [34, 2 + s * 6], [44, 4 + s * 6], [38, 20]], 'W');
    p.rect(44, 33, 4, 11, 'F').line(45, 28, 52, 20, 'f', 2).ell(52, 18, 2.5, 3, 'F');
    p.ell(32, 30, 14, 8, 'f');
    p.rect(38, 34, 4, 10, 'f').rect(37, 43, 6, 1, 'f');
    p.ell(18, 26, 8, 9, 'h');
    p.line(16, 33, 14, 43, 'y', 3).line(22, 33, 22, 43, 'Y', 3).dots([[12, 44], [14, 44], [16, 44], [20, 44], [22, 44], [24, 44]], 'k');
    p.ell(12, 15, 7, 7, 'h').poly([[14, 8], [20, 3], [19, 10]], 'h').poly([[17, 9], [24, 6], [21, 12]], 'H');
    p.poly([[0, 16], [6, 12], [7, 19], [3, 20]], 'y').px(0, 17, 'y').px(1, 18, 'k');
    p.dots([[8, 13], [9, 13]], 'e');
    const up = s ? 10 : 0;
    p.poly([[22, 24], [28, 8 + up], [40, 0 + up], [52, 2 + up], [46, 8 + up], [50, 11 + up], [42, 14 + up], [46, 17 + up], [34, 23]], 'w');
    p.path([[29, 12 + up], [36, 8 + up], [44, 7 + up]], 'W', 1).path([[30, 17 + up], [38, 13 + up], [44, 12 + up]], 'W', 1);
    p.path([[33, 4 + up], [36, 9 + up], [34, 10 + up], [38, 16 + up]], 'z', 1);
    return p.rows();
  }
  def('b_griffin', { f: RAMP.sand, h: RAMP.cloud, y: RAMP.gold, w: RAMP.blue, k: P.ink, e: P.cyan, z: P.yellow }, [griffin(0), griffin(1)], { ox: 27, oy: 45 });

  // ---------------------------------------------------------------
  //  ITEM ICONS (16 × 16) — 'e' gem/accent follows rarity
  // ---------------------------------------------------------------
  const ICON = { ox: 0, oy: 0 };
  def('a_leather', { l: RAMP.brown, b: RAMP.wood, g: P.amber, e: P.green }, [`
................
....ll....ll....
...llll..llll...
..lllllllllllll.
..lllLllllLllll.
...llLlllLllll..
....lLlllLlll...
....llLlLllll...
....lllLlllll...
....llllllll....
....bbbgbbbb....
....llllllll....
....lLllllLl....
....llllllll....
................
................`], ICON);
  def('a_chain', { c: RAMP.steel, d: P.dusk, b: RAMP.wood, e: P.cyan }, [`
................
...cccc..cccc...
..cccccccccccc..
.cccdcdcdcdcccc.
.ccdcdcdcdcdccc.
.cc.cdcdcdcd.cc.
.cc.dcdcdcdc.cc.
....cdcdcdcd....
....dcdcdcdc....
....cdcdcdcd....
....bbbbbbbb....
....cdcdcdcd....
....dcdcdcdc....
....cccccccc....
................
................`], ICON);
  def('a_plate', { p: RAMP.silver, g: RAMP.gold, e: P.red }, [`
................
.ppp........ppp.
pppppp....pppppp
pppppppppppppppp
.pppPpppppppPpp.
...ppPppppPppp..
...pppPppPpppp..
...ppppPPppppp..
...ppppgeppppp..
...pppppgppppp..
....pppppppppp..
....pPPPPPPPPp..
....pppppppppp..
.....pp....pp...
................
................`], ICON);
  def('a_robe', { r: RAMP.blue, g: RAMP.gold, e: P.cyan, k: P.ink }, [`
......rrrr......
.....rrrrrr.....
....rrkkkkrr....
....rrkkkkrr....
...rrrgrrgrrr...
..rrrrrgggrrrr..
..rrr.rrrrr.rrr.
..rr..rrrrr..rr.
......rrgrr.....
.....rrrgrrr....
.....rrrgrrr....
....rrrrgrrrr...
....rrrrgrrrr...
...rrrrrgrrrrr..
...ggggggggggg..
................`], ICON);
  def('c_ring', { g: RAMP.gold, e: P.red, w: P.white }, [`
................
................
.......ee.......
......eewe......
......eeee......
.......ee.......
.....gggggg.....
....gg....gg....
...gg......gg...
...g........g...
...g........g...
...gg......gg...
....gg....gg....
.....gggggg.....
................
................`], ICON);
  def('c_amulet', { g: RAMP.gold, e: P.cyan, w: P.white }, [`
....g......g....
....g......g....
.....g....g.....
.....g....g.....
......g..g......
......gggg......
.....gggggg.....
....gggeeggg....
....ggewweegg...
....geeweeeg....
.....geeeeg.....
......geeg......
.......gg.......
................
................
................`], ICON);
  def('c_charm', { c: RAMP.brown, f: RAMP.bone, e: P.red, b: RAMP.wood }, [`
................
...c.........c..
....c.......c...
.....c.....c....
......c...c.....
.......ccc......
.......beb......
......ffff......
......ffff......
.......fff......
.......ff.......
.......ff.......
........f.......
................
................
................`], ICON);
  def('m_hunter', { r: RAMP.red, g: RAMP.fire, k: P.soil, e: P.red }, [`
....rrr..rrr....
....rRr..rRr....
....rRr..rRr....
.....rr..rr.....
......rrrr......
.....gggggg.....
....gggggggg....
...ggkgggggkg...
...gggkgggkgg...
...ggggkgkggg...
...gggggkgggg...
...ggggkgkggg...
....gkggggkg....
.....gggggg.....
................
................`], ICON);
  def('m_seeker', { r: RAMP.blue, g: RAMP.silver, k: P.dusk, e: P.cyan }, [`
....rrr..rrr....
....rRr..rRr....
....rRr..rRr....
.....rr..rr.....
......rrrr......
.....gggggg.....
....gggggggg....
...gggkkkkggg...
...ggkeeeekgg...
...gkeekkeekg...
...ggkeeeekgg...
...gggkkkkggg...
....gggggggg....
.....gggggg.....
................
................`], ICON);
  def('m_honor', { r: RAMP.purple, g: RAMP.gold, k: P.rust, e: P.white }, [`
....rrr..rrr....
....rRr..rRr....
....rRr..rRr....
.....rr..rr.....
......rrrr......
.....gggggg.....
....gggkgggg....
...ggggkkgggg...
...gkkkekkkkg...
...ggkkkkkkgg...
...gggkkkkggg...
...ggkkggkkgg...
....gggggggg....
.....gggggg.....
................
................`], ICON);

  // ---------------------------------------------------------------
  //  SKILL ICONS (16 × 16)
  // ---------------------------------------------------------------
  def('s_cleave', { w: RAMP.ice, y: P.yellow, r: RAMP.brown }, [`
..........www...
............ww..
.............ww.
..............w.
..............ww
...............w
..............ww
.............ww.
...........www..
.......wwwww....
....wwwww.......
..ww............
................
.rr..rrr...rr...
rrrrrrrrrrrrrrrr
.r....r....r....`], ICON);
  def('s_flurry', { w: RAMP.silver, y: P.yellow }, [`
................
............y...
...........yy...
.......wwwww....
..wwwwwww.......
............y...
..........yyy...
....wwwwwwww....
.wwwwww.........
................
............y...
...........yy...
.....wwwwwww....
..wwwwww........
................
................`], ICON);
  def('s_warcry', { g: RAMP.gold, r: RAMP.red, w: P.white }, [`
................
..............w.
............w.w.
...gg......w..w.
..gggg........w.
.gggggg....w..w.
.ggggggggg..w.w.
.ggggggggggg..w.
.gggggggggggg...
..gggggggggrr...
...gggggggrr....
.....ggg.rr.....
......rrrr......
................
................
................`], ICON);
  def('s_thunder', { y: RAMP.gold, w: P.white }, [`
........yyyy....
.......yyyy.....
......yyyy......
.....yyyy.......
....yyyyyyyy....
.......yyyy.....
......yyyy......
.....yyyy.......
....yyyyyyyy....
.......yyy......
......yyy.......
.....yy.........
....yw..........
...w............
................
................`], ICON);
  def('s_bastion', { s: RAMP.silver, b: RAMP.blue, g: P.amber }, [`
................
..ssssssssssss..
..sbbbbbbbbbbs..
..sbbbbbbbbbbs..
..sbbbgggbbbbs..
..sbbgbbbgbbbs..
..sbbgbbbgbbbs..
..sbbbgggbbbbs..
..sbbbbbbbbbbs..
...sbbbbbbbbs...
...sbbbbbbbbs...
....sbbbbbbs....
.....sbbbbs.....
......ssss......
................
................`], ICON);
  def('s_meteor', { f: RAMP.fire, r: RAMP.lava, y: P.yellow }, [`
y...............
.y..............
..yy............
...rr...........
....rr..........
.....rrr........
......rrr.......
.......rrfff....
........fffff...
........ffyfff..
........fyyyff..
........ffyfff..
.........ffff...
..........ff....
................
................`], ICON);
  def('s_gale', { c: RAMP.ice }, [`
................
.....ccccc......
...cc.....cc....
..c...ccc...c...
..c..c...c..c...
..c..c.c..c.c...
..c...cc..c.c...
...c.....c..c...
....ccccc..c....
..........c.....
.cccc...cc......
.....ccc........
...cccccccc.....
................
................
................`], ICON);
  def('s_soul', { p: RAMP.purple, k: P.ink, c: P.cyan }, [`
.......pp.......
......pppp......
.....pppppp.....
....pppppppp....
....pppppppp....
....pkkppkkp....
....pkcppkcp....
....pppppppp....
.....ppkkpp.....
.....pppppp.....
......pppp.p....
.....p.pp.......
....p..p...p....
.......p........
................
................`], ICON);
  def('s_snare', { s: RAMP.steel, r: RAMP.brown }, [`
................
................
..s..s..s..s....
..ss.ss.ss.ss...
..sssssssssss...
..s.........s...
..s.........s...
..sssssssssss...
..ss.ss.ss.ss...
..s..s..s..s....
.....rrrrr......
....rr...rr.....
.........rrrrrr.
................
................
................`], ICON);
  def('s_storm', { g: RAMP.gold, w: P.white }, [`
................
.......ggg......
......ggggg.....
......ggwgg.....
.ggg...ggg......
ggggg.......ggg.
ggwgg......ggggg
.ggg.......ggwgg
............ggg.
.....ggg........
....ggggg.......
....ggwgg.......
.....ggg........
................
................
................`], ICON);
  def('s_execute', { s: RAMP.silver, r: RAMP.red, b: RAMP.wood }, [`
.......bb.......
.......bb.......
......bbbb......
.......ss.......
......ssss......
.....ssssss.....
.....ssssss.....
.....ssssss.....
.....ssssss.....
.....ssssss.....
.....ssssss.....
......ssss......
.......ss.......
.......rr.......
......rrrr......
.......rr.......`], ICON);
  def('s_nova', { g: RAMP.green, y: P.yellow }, [`
.......g........
.......g........
...g...g...g....
....g..g..g.....
.....ggggg......
......ggg.......
.gggggyyyggggg..
......ggg.......
.....ggggg......
....g..g..g.....
...g...g...g....
.......g........
.......g........
................
................
................`], ICON);

  // ---------------------------------------------------------------
  //  UI ICONS (9 × 9)
  // ---------------------------------------------------------------
  def('i_gold', { g: RAMP.gold, w: P.white, k: P.rust }, [`
..ggggg..
.ggggggg.
ggwkkkggg
ggwkggggg
ggwkkkggg
gggggkggg
ggkkkkggg
.ggggggg.
..ggggg..`], ICON);
  def('i_dust', { d: RAMP.purple, c: P.cyan, w: P.white }, [`
....w....
...wcw...
....w....
.........
...ddd...
..ddddd..
.ddcdddd.
ddddddcdd
ddddddddd`], ICON);
  def('i_badge', { g: RAMP.gold, w: P.white }, [`
....g....
...ggg...
gggggggg.
.ggwggg..
..ggggg..
.ggg.ggg.
.gg...gg.
.g.....g.
.........`], ICON);
  def('i_atk', { s: RAMP.silver, g: P.amber, b: RAMP.wood }, [`
.......ss
......sss
.....sss.
....sss..
.g.sss...
..gss....
..bg.....
.b..g....
b........`], ICON);
  def('i_spd', { c: RAMP.ice }, [`
.........
..cccc...
.......c.
.ccccccc.
.........
ccccccc..
........c
..ccccc..
.........`], ICON);
  def('i_crit', { r: RAMP.red, w: P.white }, [`
....r....
..rrrrr..
.r..r..r.
.r..r..r.
rrrrwrrrr
.r..r..r.
.r..r..r.
..rrrrr..
....r....`], ICON);
  def('i_cdmg', { y: RAMP.fire, w: P.yellow }, [`
....y....
.y..y..y.
..yyyyy..
..yywyy..
yyywwwyyy
..yywyy..
..yyyyy..
.y..y..y.
....y....`], ICON);
  def('i_hp', { r: RAMP.red, w: P.white }, [`
.........
.rr...rr.
rrrr.rrrr
rwrrrrrrr
rrrrrrrrr
.rrrrrrr.
..rrrrr..
...rrr...
....r....`], ICON);
  def('i_arm', { s: RAMP.silver, b: RAMP.blue }, [`
sssssssss
sbbbbbbbs
sbbsbbbbs
sbbsbbbbs
sbbbbbbbs
.sbbbbbs.
.sbbbbbs.
..sbbbs..
...sss...`], ICON);
  def('i_ls', { r: RAMP.red, w: P.white }, [`
....r....
....r....
...rrr...
...rrr...
..rrrrr..
.rwrrrrr.
.rwrrrrr.
.rrrrrrr.
..rrrrr..`], ICON);
  def('i_regen', { g: RAMP.green, w: P.white }, [`
...ggg...
...gwg...
...ggg...
ggggggggg
gwwgggggg
ggggggggg
...ggg...
...ggg...
...ggg...`], ICON);
  def('i_loot', { b: RAMP.wood, g: RAMP.gold, k: P.ink }, [`
.........
.bbbbbbb.
bbbbbbbbb
bgggggggb
bbbbkbbbb
bbbbgbbbb
bbbbbbbbb
bbbbbbbbb
.........`], ICON);
  def('i_skull', { b: RAMP.bone, k: P.ink }, [`
..bbbbb..
.bbbbbbb.
bbbbbbbbb
bkkbbbkkb
bkkbbbkkb
bbbbkbbbb
.bbbbbbb.
.bkbkbkb.
..bbbbb..`], ICON);
  def('i_board', { p: RAMP.sand, k: P.bark, r: P.red }, [`
ppppppppp
pkkkkkkpp
ppppppppp
pkkkkkppp
ppppppppp
pkkkkkkkp
ppppppprp
pkkkkpprr
ppppppppp`], ICON);
  def('i_mine', { s: RAMP.silver, b: RAMP.wood }, [`
..sssss..
.ss...ss.
ss..b..ss
s...b...s
....b....
....b....
....b....
....b....
....b....`], ICON);
  def('i_rush', { g: RAMP.gold, r: P.red }, [`
.........
g...g...g
gg.ggg.gg
ggggggggg
ggrgggrgg
ggggggggg
ggggggggg
.........
.........`], ICON);
  def('i_trial', { p: RAMP.purple, g: RAMP.gold, w: P.white }, [`
ggggggggg
.ppppppp.
..pwppp..
...ppp...
....p....
...p.p...
..p.w.p..
.ppppppp.
ggggggggg`], ICON);
  def('i_lock', { s: RAMP.steel, g: RAMP.gold }, [`
..sssss..
.s.....s.
.s.....s.
ggggggggg
gggg.gggg
gggg.gggg
ggggggggg
ggggggggg
.........`], ICON);
  def('i_sound', { s: RAMP.silver }, [`
....s....
...ss..s.
sssss...s
sssss.s.s
sssss.s.s
sssss...s
...ss..s.
....s....
.........`], ICON);
  def('i_gear', { s: RAMP.silver, k: P.dusk }, [`
...s.s...
.sssssss.
.ss...ss.
sss.k.sss
.s.kkk.s.
sss.k.sss
.ss...ss.
.sssssss.
...s.s...`], ICON);
  def('i_pip', { s: RAMP.silver, b: RAMP.blue }, [`
sssssssss
s.......s
s.......s
s....bbbs
s....bbbs
sssssssss
.........
.........
.........`], ICON);
  def('i_full', { s: RAMP.silver }, [`
sss...sss
s.......s
s.......s
.........
.........
.........
s.......s
s.......s
sss...sss`], ICON);
  def('i_star', { y: RAMP.gold }, [`
....y....
....y....
...yyy...
yyyyyyyyy
.yyyyyyy.
..yyyyy..
..yy.yy..
.yy...yy.
.........`], ICON);
  def('i_rune', { c: RAMP.ice, k: P.navy }, [`
...ccc...
..ccccc..
.cckckcc.
cccckcccc
cckkkkkcc
cccckcccc
.cckckcc.
..ccccc..
...ccc...`], ICON);
  def('i_up', { g: RAMP.green }, [`
....g....
...ggg...
..ggggg..
.ggggggg.
...ggg...
...ggg...
...ggg...
.........
.........`], ICON);
  def('i_down', { r: RAMP.red }, [`
.........
...rrr...
...rrr...
...rrr...
.rrrrrrr.
..rrrrr..
...rrr...
....r....
.........`], ICON);

  // loot bag drop / coin spin
  def('coin', { g: RAMP.gold, w: P.white }, [`
.ggg.
ggwgg
ggggg
ggggg
.ggg.`, `
..g..
.gwg.
.ggg.
.ggg.
..g..`, `
..g..
..g..
..w..
..g..
..g..`, `
..g..
.ggg.
.ggw.
.ggg.
..g..`], { ox: 2, oy: 4 });

  // projectiles
  def('p_sting', { k: P.ink, y: P.amber }, [`yykk`], { outline: false, ox: 0, oy: 0 });
  def('p_needle', { w: P.cream, g: P.leaf }, [`wwwwg`], { outline: false, ox: 0, oy: 0 });
  def('p_fireball', { f: RAMP.fire }, [`
..fff.
.fffff
ffffff
.fffff
..fff.`], { ox: 3, oy: 2 });
  def('p_wispfire', { w: RAMP.ice }, [`
..w..
.www.
wwwww
.www.`], { ox: 2, oy: 2 });
  def('p_feather', { f: RAMP.sand }, [`
....ff.
ffffff.
.ffff..`], { ox: 3, oy: 1 });
  def('p_spark', { y: P.yellow, w: P.white }, [`
..y..
.ywy.
ywwwy
.ywy.
..y..`], { outline: false, ox: 2, oy: 2 });
  def('p_lava', { l: RAMP.lava }, [`
.lll.
lllll
lllll
.lll.`], { ox: 2, oy: 2 });

  return { RAMP, S, def, grid, bake, heroGrid, HERO_POSES, COATS, BLADE, GEM, GRIP, Paint, VARIANTS: {} };
})();
